version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: healthcare-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            MYSQL_DATABASE: healthcare
            MYSQL_ROOT_PASSWORD: hailuong1012
            DB_DATABASE: healthcare
            DB_USERNAME: root
            DB_PASSWORD: hailuong1012
        depends_on:
            - redis
        networks:
            - healthcare

    # nginx
    nginx:
        image: nginx:alpine
        container_name: healthcare-nginx
        restart: unless-stopped
        ports:
            - "443:443"
        volumes:
            - ./:/var/www
            - ./dev/nginx/:/etc/nginx/conf.d/
        networks:
            - healthcare

    # db mysql
    db:
        image: mysql:latest
        container_name: healthcare-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: healthcare
            MYSQL_ROOT_PASSWORD: hailuong1012
            MYSQL_PASSWORD: hailuong1012
            MYSQL_USER: root
        volumes:
            - dbdata:/var/lib/mysql/
            - ./dev/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        networks:
            - healthcare

    # redis
    redis:
        image: redis:latest
        container_name: healthcare-redis
        networks:
            - healthcare

#Docker Networks
networks:
    healthcare:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
